name: BlokClaims-recoded
version: 2.0.0
api-version: 1.16
main: mc.obliviate.blokclaims.BlokClaims
authors: [ Mr_Obliviate, HakanKargın ]
description: Custom claim management plugin for Blok Dünyası!
softdepend: [ Vault, HolographicDisplays ]
commands:
  blokClaim:
    aliases: [ blokclaim, blokclaims, claim ]